USE [infrend]
GO
/****** Object:  Table [dbo].[LG_PROCESSAMENTO]    Script Date: 02/08/2013 09:47:32 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[LG_PROCESSAMENTO](
	[ID_LG_PROCESSAMENTO] [bigint] IDENTITY(1,1) NOT NULL,
	[DT_ERROR] [datetime] NOT NULL,
	[NU_ERROR] [int] NOT NULL,
	[NU_SEVERITY] [int] NOT NULL,
	[NU_STATE] [int] NOT NULL,
	[NO_PROCEDURE] [nvarchar](128) NOT NULL,
	[NU_LINE] [int] NOT NULL,
	[DS_MESSAGE] [nvarchar](4000) NOT NULL,
	[TX_DETALHE] [nvarchar](255) NULL,
	[TX_REGISTRO] [varchar](4000) NULL,
 CONSTRAINT [PK_LG_PROCESSAMENTO] PRIMARY KEY CLUSTERED 
(
	[ID_LG_PROCESSAMENTO] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF